FROM node:16.13.1 as build-stage

CMD mkdir /srv/cf.database

COPY ["package.json","/srv/cf.database/"]

WORKDIR /srv/cf.database

RUN npm install

COPY [".", "/srv/cf.database/"]

EXPOSE 80

CMD [ "npm", "run", "dev" ]
